version: "3"

services:
  database:
    image: postgres:latest
    container_name: event-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: events
      PGDATA: /var/lib/postgresql/data
    volumes:
      - "${HOME}/mnt/events/data:/var/lib/postgresql/data"
    ports:
      - "59111:5432"

  pulsar:
    image: apachepulsar/pulsar
    container_name: pulsar-pub-sub
    restart: on-failure
    volumes:
      - "${HOME}/storage/data/pulsar:/pulsar/data"
    ports:
      - "6650:6650"
      - "8090:8080"
    command: bin/pulsar standalone

  destroyer:
    build:
      context: ./destroyer
    environment:
      PULSAR_URL: pulsar://pulsar:6650
      DATABASE_URL: postgres://postgres:root@database:5432/events?sslmode=disable
      PORT: 30001
    ports:
      - "30001:30001"
    restart: on-failure
    depends_on:
      - pulsar
      - database

  dealthstar:
    build:
      context: ./dealthstar
    environment:
      PULSAR_URL: pulsar://pulsar:6650
      DATABASE_URL: postgres://postgres:root@database:5432/events?sslmode=disable
      PORT: 30002
    depends_on:
      - database
      - pulsar
    restart: on-failure
    ports:
      - "30002:30002"

  api-gateway:
    build:
      context: ./api
    environment:
      DESTROYER_URL: destroyer:30001
      PORT: 2004
    restart: on-failure
    depends_on:
      - destroyer
    ports:
      - "2004:2004"
